# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCAutoCircleScrollViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SCAutoCircleScrollViewDemo

pod 'SDWebImage', '~> 4.0.0'

  target 'SCAutoCircleScrollViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCAutoCircleScrollViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
